In [1201]:
import numpy

In [1202]:
a=[1, 2.5 ,3]
b=[1, 3.3 ,5]

In [1203]:
a = numpy.array(a)

In [1204]:
b = numpy.array(b)

In [1205]:
c = a*b

In [1206]:
c

array([ 1.  ,  8.25, 15.  ])

In [1207]:
###

In [1208]:
c = numpy.array(c, dtype = "int") #böyle yaparsak tüm sayilar int tipinde tutulur.

In [1209]:
c

array([ 1,  8, 15])

In [1210]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1211]:
numpy.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1212]:
numpy.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [1213]:
numpy.arange(0,10,2) # 0'dan 10'a kadar 2 arttirarak git. (10 dahil degil)

array([0, 2, 4, 6, 8])

In [1214]:
numpy.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [1215]:
numpy.random.normal(10, 4, (3,4)) # standart sapmali istatiktik konulu bir sey.

array([[11.0555577 , 10.88779954,  7.59463647, 10.74301733],
       [11.02844652, 15.05254005,  6.92299511,  8.1539421 ],
       [ 8.68319677, 15.80232397,  9.40254098, 11.22345393]])

In [1216]:
a = numpy.random.randint(0,10, (3,3))
b = numpy.random.randint(0,10, (3,3))

In [1217]:
a

array([[1, 7, 7],
       [4, 2, 1],
       [1, 6, 0]])

In [1218]:
b

array([[2, 8, 5],
       [1, 4, 0],
       [3, 3, 0]])

In [1219]:
# ndim: boyut sayisi
# shape: boyut bilgisi
# size: eleman sayisi
# dtype: veri tipi

In [1220]:
a.ndim

2

In [1221]:
a.shape

(3, 3)

In [1222]:
a.size

9

In [1223]:
a.dtype

dtype('int64')

In [1224]:
a.reshape(1,9) # 3x3lük matrisi 1x9luk matrise dönüstürür.

array([[1, 7, 7, 4, 2, 1, 1, 6, 0]])

In [1225]:
numpy.concatenate([a,b]) # 2 matrisi alt alta birlestirdik.

array([[1, 7, 7],
       [4, 2, 1],
       [1, 6, 0],
       [2, 8, 5],
       [1, 4, 0],
       [3, 3, 0]])

In [1226]:
c = numpy.concatenate([a,b] , axis=1) # 2 matrisi yan yana birlestirdik.

In [1227]:
c

array([[1, 7, 7, 2, 8, 5],
       [4, 2, 1, 1, 4, 0],
       [1, 6, 0, 3, 3, 0]])

In [1228]:
numpy.vsplit(c, [1,2]) # 1 satirin altindan bi kes, sonra 2 satirin altinda kes. (böylece 3'e bölmüs olduk.)

[array([[1, 7, 7, 2, 8, 5]]),
 array([[4, 2, 1, 1, 4, 0]]),
 array([[1, 6, 0, 3, 3, 0]])]

In [1229]:
numpy.hsplit(c, [1,3]) # 1 sütunun sagindan bi kes, sonra 3. sütunun sagindan kes. (böylece 3'e bölmüs olduk.)

[array([[1],
        [4],
        [1]]),
 array([[7, 7],
        [2, 1],
        [6, 0]]),
 array([[2, 8, 5],
        [1, 4, 0],
        [3, 3, 0]])]

In [1230]:
numpy.split(c[0], [2,4]) # 2.nin sagindan bi kes, sonra 4.nün sagindan kes. (böylece 3'e bölmüs olduk.)

[array([1, 7]), array([7, 2]), array([8, 5])]

In [1231]:
x , y , z = numpy.split(c[0], [2,4]) # 2.nin sagindan bi kes, sonra 4.nün sagindan kes. (böylece 3'e bölmüs olduk.)

In [1232]:
x

array([1, 7])

In [1233]:
y

array([7, 2])

In [1234]:
z

array([8, 5])

In [1235]:
numpy.sort(z) # degerleri kücükten büyüge siralar.

array([5, 8])

In [1236]:
c

array([[1, 7, 7, 2, 8, 5],
       [4, 2, 1, 1, 4, 0],
       [1, 6, 0, 3, 3, 0]])

In [1237]:
numpy.sort(c, axis=1) # her bir satiri kendi icinde siraladi.

array([[1, 2, 5, 7, 7, 8],
       [0, 1, 1, 2, 4, 4],
       [0, 0, 1, 3, 3, 6]])

In [1238]:
numpy.sort(c, axis=0) # her bir sütunu kendi icinde siraladi.

array([[1, 2, 0, 1, 3, 0],
       [1, 6, 1, 2, 4, 0],
       [4, 7, 7, 3, 8, 5]])

In [1239]:
c

array([[1, 7, 7, 2, 8, 5],
       [4, 2, 1, 1, 4, 0],
       [1, 6, 0, 3, 3, 0]])

In [1240]:
c[0,1] # 0. satirin 1. sütunundaki degeri döndürme.

7

In [1241]:
c

array([[1, 7, 7, 2, 8, 5],
       [4, 2, 1, 1, 4, 0],
       [1, 6, 0, 3, 3, 0]])

In [1242]:
c[:,0] # 0. sütun; tüm sütunlar. al.

array([1, 4, 1])

In [1243]:
c[0,:] # 0. satir; tüm sütunlar. al.

array([1, 7, 7, 2, 8, 5])

In [1244]:
c[0,1:] # 0. satir; 1. sütundan basla tüm sütunlari al.

array([7, 7, 2, 8, 5])

In [1245]:
c[0:2 , 0:3] # 0'dan 2'ye kadar satirlar, 0'dan 3'e kadar sütunlar. al. (2 ve 3 dahil degil.)c

array([[1, 7, 7],
       [4, 2, 1]])

In [1246]:
d = c[0:2 , 0:3] # örnegin matrisin alt kümesini alip d[0:0] = 2 yaparsak, bu orijinal c matrisini de bozar. Bundan kacinmak icin. e = d.copy() yaparak matrisin kopyasini alip kopyasi üzerinden islem yapmak gerekir.

In [1247]:
###

In [1248]:
###

In [1249]:
###

In [1250]:
# Fancy Index

In [1251]:
a1 = numpy.random.randint(0 , 10 , (6,6))
a1

array([[0, 7, 3, 7, 3, 3],
       [0, 7, 5, 5, 0, 0],
       [4, 2, 9, 4, 7, 2],
       [3, 5, 9, 4, 7, 1],
       [8, 6, 1, 3, 5, 6],
       [2, 7, 0, 1, 4, 1]])

In [1252]:
a1[0][[1,3,5]] # index erisimini bu sekilde toplu olarak da yapabiliriz.

array([7, 7, 3])

In [1253]:
a1[0, [1,3,5]]

array([7, 7, 3])

In [1254]:
a1[1:, [1,3,5]]

array([[7, 5, 0],
       [2, 4, 2],
       [5, 4, 1],
       [6, 3, 6],
       [7, 1, 1]])

In [1255]:
satir = numpy.array([3,5,2])
satir

array([3, 5, 2])

In [1256]:
sutun = numpy.array([1,3,4])
sutun

array([1, 3, 4])

In [1257]:
a1[satir, sutun] # 3. satirin 1. indexini al, 5. satirin 3. indexini al, 2. satirin 4. indexini al, yan yana koy.

array([5, 1, 7])

In [1258]:
a1

array([[0, 7, 3, 7, 3, 3],
       [0, 7, 5, 5, 0, 0],
       [4, 2, 9, 4, 7, 2],
       [3, 5, 9, 4, 7, 1],
       [8, 6, 1, 3, 5, 6],
       [2, 7, 0, 1, 4, 1]])

In [1259]:
a1 < 2

array([[ True, False, False, False, False, False],
       [ True, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False,  True, False, False, False],
       [False, False,  True,  True, False,  True]])

In [1260]:
a1 * 2

array([[ 0, 14,  6, 14,  6,  6],
       [ 0, 14, 10, 10,  0,  0],
       [ 8,  4, 18,  8, 14,  4],
       [ 6, 10, 18,  8, 14,  2],
       [16, 12,  2,  6, 10, 12],
       [ 4, 14,  0,  2,  8,  2]])

In [1261]:
b1 = numpy.random.randint(0 , 10 , (3,3))
b1

array([[3, 1, 9],
       [6, 7, 6],
       [4, 5, 6]])

In [1262]:
numpy.add(b1, 1)

array([[ 4,  2, 10],
       [ 7,  8,  7],
       [ 5,  6,  7]])

In [1263]:
numpy.subtract(b1, 1)

array([[2, 0, 8],
       [5, 6, 5],
       [3, 4, 5]])

In [1264]:
numpy.multiply(b1, 2)

array([[ 6,  2, 18],
       [12, 14, 12],
       [ 8, 10, 12]])

In [1265]:
numpy.divide(b1, 2)

array([[1.5, 0.5, 4.5],
       [3. , 3.5, 3. ],
       [2. , 2.5, 3. ]])

In [1266]:
numpy.power(b1, 2)

array([[ 9,  1, 81],
       [36, 49, 36],
       [16, 25, 36]])

In [1267]:
numpy.mod(b1, 3)

array([[0, 1, 0],
       [0, 1, 0],
       [1, 2, 0]])

In [1268]:
numpy.absolute(numpy.array([-5])) # 5'in mutlak degerini aldik.

array([5])

In [1269]:
numpy.sin(180)

-0.8011526357338306

In [1270]:
numpy.cos(0)

1.0

In [1271]:
b1

array([[3, 1, 9],
       [6, 7, 6],
       [4, 5, 6]])

In [1272]:
numpy.log2(b1) # logaritma alma.

array([[1.5849625 , 0.        , 3.169925  ],
       [2.5849625 , 2.80735492, 2.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

In [1273]:
numpy.log10(b1) # logaritma alma.

array([[0.47712125, 0.        , 0.95424251],
       [0.77815125, 0.84509804, 0.77815125],
       [0.60205999, 0.69897   , 0.77815125]])

In [1274]:
# Iki bilinmeyenli denklem cözümü
# 5x + 2y = 12
# 2x + 5y = 10

In [1275]:
katsayilar = numpy.array([[5,2],[2,5]])
sonuclar = numpy.array([12,10])

In [1276]:
numpy.linalg.solve(katsayilar, sonuclar)

array([1.9047619 , 1.23809524])

# PANDAS

In [1277]:
import pandas

In [1278]:
seri1=pandas.Series([1,3,5,7])

In [1279]:
seri1.axes # serinin index bilgilerine erisme

[RangeIndex(start=0, stop=4, step=1)]

In [1280]:
seri1.dtype # serinin tipi

dtype('int64')

In [1281]:
seri1.size # serinin eleman sayisi

4

In [1282]:
seri1.ndim # serinin boyutu

1

In [1283]:
seri1.values # seriyi bir vektör, yani bir dizi olarak ele alma

array([1, 3, 5, 7])

In [1284]:
seri1.head(2) # serinin ilk 2 gözlemini getirme.

0    1
1    3
dtype: int64

In [1285]:
seri1.tail(2) # serinin son 2 gözlemini getirme.

2    5
3    7
dtype: int64

In [1286]:
seri2 = pandas.Series([22,11,33,55,44], index = ["a",3,"b",7,"c"])
# serideki elemanlari bu sekilde kendimiz de indexleyebiliriz.
seri2

a    22
3    11
b    33
7    55
c    44
dtype: int64

In [1287]:
seri2["c"]

44

In [1288]:
seri2["a":"b"]

a    22
3    11
b    33
dtype: int64

In [1289]:
seri3 = pandas.Series({"isim":"enes","yas":28})
seri3

isim    enes
yas       28
dtype: object

In [1290]:
pandas.concat([seri2,seri3])

a         22
3         11
b         33
7         55
c         44
isim    enes
yas       28
dtype: object

In [1291]:
seri2

a    22
3    11
b    33
7    55
c    44
dtype: int64

In [1292]:
seri2.index

Index(['a', 3, 'b', 7, 'c'], dtype='object')

In [1293]:
seri2.values

array([22, 11, 33, 55, 44])

In [1294]:
seri2.keys

<bound method Series.keys of a    22
3    11
b    33
7    55
c    44
dtype: int64>

In [1295]:
list(seri2.items())

[('a', 22), (3, 11), ('b', 33), (7, 55), ('c', 44)]

In [1296]:
"b" in seri2

True

### PANDAS DATAFRAME

In [1297]:
pandas.DataFrame(["python", "javascript", "c#"], columns=["programlama dilleri"])

programlama dilleri
0              python
1          javascript
2                  c#

In [1298]:
a = numpy.arange(0,18,2).reshape((3,3)) # 0'dan 10'a kadar 2 arttirarak git. (10 dahil degil)
a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [1299]:
b = pandas.DataFrame(a, columns=["a","b","c"])
b

a   b   c
0   0   2   4
1   6   8  10
2  12  14  16

In [1300]:
b.columns

Index(['a', 'b', 'c'], dtype='object')

In [1301]:
b.columns = ("x","y","z")
b

x   y   z
0   0   2   4
1   6   8  10
2  12  14  16

In [1302]:
b.ndim

2

In [1303]:
b.shape

(3, 3)

In [1304]:
b.size

9

In [1305]:
b.axes

[RangeIndex(start=0, stop=3, step=1), Index(['x', 'y', 'z'], dtype='object')]

In [1306]:
b.values

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [1307]:
b.head(1)

x  y  z
0  0  2  4

In [1308]:
b.tail(1)

x   y   z
2  12  14  16

In [1309]:
###

In [1310]:
s1 = numpy.random.randint(10, size = 5)
s2 = numpy.random.randint(10, size = 5)
s3 = numpy.random.randint(10, size = 5)

In [1311]:
s1

/Users/esadsiz/opt/anaconda3/lib/python3.9/site-packages/IPython/core/displayhook.py:275: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


array([7, 0, 8, 3, 5])

In [1312]:
s2

array([9, 1, 9, 0, 9])

In [1313]:
s3

array([6, 7, 7, 2, 8])

In [1314]:
tabloverileri = {"var1":s1, "var2":s2, "var3":s3}

In [1315]:
tablo = pandas.DataFrame(tabloverileri)
tablo

var1  var2  var3
0     7     9     6
1     0     1     7
2     8     9     7
3     3     0     2
4     5     9     8

In [1316]:
tablo[1:3]

var1  var2  var3
1     0     1     7
2     8     9     7

In [1317]:
tablo.index

RangeIndex(start=0, stop=5, step=1)

In [1318]:
tablo.index=["a","b","c","d","e"]
tablo

var1  var2  var3
a     7     9     6
b     0     1     7
c     8     9     7
d     3     0     2
e     5     9     8

In [1319]:
tablo.drop("a", axis=0)

var1  var2  var3
b     0     1     7
c     8     9     7
d     3     0     2
e     5     9     8

In [1320]:
tablo.drop("a", axis=0) # satir silme

var1  var2  var3
b     0     1     7
c     8     9     7
d     3     0     2
e     5     9     8

In [1321]:
tablo.drop("a", axis=0, inplace=True) # satiri kalici olarak silme.
# "a" yerine coklu olarak ["a","b"] seklinde de yazabiliriz. 
tablo

var1  var2  var3
b     0     1     7
c     8     9     7
d     3     0     2
e     5     9     8

In [1322]:
tablo["var3 / var2"] = tablo["var3"] / tablo["var2"]
tablo

var1  var2  var3  var3 / var2
b     0     1     7     7.000000
c     8     9     7     0.777778
d     3     0     2          inf
e     5     9     8     0.888889

### loc & iloc

In [1323]:
m = numpy.random.randint(1,30, size=(10,3))
tablo = pandas.DataFrame(m, columns = ["var1","var2","var3"])
tablo

var1  var2  var3
0    21     9    10
1    14    20     1
2    28    28     6
3    25     9     6
4     7    14    20
5    18    15     2
6     4    22     4
7    14    14    13
8    13     7    18
9    24     9    24

In [1324]:
tablo.loc[1:2]

var1  var2  var3
1    14    20     1
2    28    28     6

In [1325]:
tablo.loc[1:3, "var2"]

1    20
2    28
3     9
Name: var2, dtype: int64

In [1326]:
tablo.iloc[1:2]

var1  var2  var3
1    14    20     1

In [1327]:
tablo.iloc[:3,:2] # ilk 3 satir ve ilk 2 sütun

var1  var2
0    21     9
1    14    20
2    28    28

In [1328]:
tablo[tablo.var1 > 15]

var1  var2  var3
0    21     9    10
2    28    28     6
3    25     9     6
5    18    15     2
9    24     9    24

In [1329]:
tablo[(tablo.var1 > 15) & (tablo.var2 < 15)]

var1  var2  var3
0    21     9    10
3    25     9     6
9    24     9    24

In [1330]:
tablo.loc[(tablo.var1 > 15) & (tablo.var2 < 15), ["var1","var2"]]

var1  var2
0    21     9
3    25     9
9    24     9

### Birlestirme Islemleri

In [1331]:
tablo1 = tablo
tablo2 = tablo + 15

In [1332]:
tablo1

var1  var2  var3
0    21     9    10
1    14    20     1
2    28    28     6
3    25     9     6
4     7    14    20
5    18    15     2
6     4    22     4
7    14    14    13
8    13     7    18
9    24     9    24

In [1333]:
tablo2

var1  var2  var3
0    36    24    25
1    29    35    16
2    43    43    21
3    40    24    21
4    22    29    35
5    33    30    17
6    19    37    19
7    29    29    28
8    28    22    33
9    39    24    39

In [1334]:
pandas.concat([tablo1,tablo2])

var1  var2  var3
0    21     9    10
1    14    20     1
2    28    28     6
3    25     9     6
4     7    14    20
5    18    15     2
6     4    22     4
7    14    14    13
8    13     7    18
9    24     9    24
0    36    24    25
1    29    35    16
2    43    43    21
3    40    24    21
4    22    29    35
5    33    30    17
6    19    37    19
7    29    29    28
8    28    22    33
9    39    24    39

In [1335]:
pandas.concat([tablo1,tablo2], ignore_index=True) 

var1  var2  var3
0     21     9    10
1     14    20     1
2     28    28     6
3     25     9     6
4      7    14    20
5     18    15     2
6      4    22     4
7     14    14    13
8     13     7    18
9     24     9    24
10    36    24    25
11    29    35    16
12    43    43    21
13    40    24    21
14    22    29    35
15    33    30    17
16    19    37    19
17    29    29    28
18    28    22    33
19    39    24    39

In [1336]:
tablo3 = pandas.DataFrame(m, columns = ["var2","var3","var4"])


In [1337]:
tablo2

var1  var2  var3
0    36    24    25
1    29    35    16
2    43    43    21
3    40    24    21
4    22    29    35
5    33    30    17
6    19    37    19
7    29    29    28
8    28    22    33
9    39    24    39

In [1338]:
tablo3

var2  var3  var4
0    21     9    10
1    14    20     1
2    28    28     6
3    25     9     6
4     7    14    20
5    18    15     2
6     4    22     4
7    14    14    13
8    13     7    18
9    24     9    24

In [1339]:
pandas.concat([tablo1,tablo3], join="inner", ignore_index=True)
# iki tabloyu sadece ortak sütunlarindan birlestirdi.

var2  var3
0      9    10
1     20     1
2     28     6
3      9     6
4     14    20
5     15     2
6     22     4
7     14    13
8      7    18
9      9    24
10    21     9
11    14    20
12    28    28
13    25     9
14     7    14
15    18    15
16     4    22
17    14    14
18    13     7
19    24     9

In [1340]:
pandas.concat([tablo1,tablo2], axis=0)
# iki tabloyu sadece ortak sütunlarindan birlestirdi.

var1  var2  var3
0    21     9    10
1    14    20     1
2    28    28     6
3    25     9     6
4     7    14    20
5    18    15     2
6     4    22     4
7    14    14    13
8    13     7    18
9    24     9    24
0    36    24    25
1    29    35    16
2    43    43    21
3    40    24    21
4    22    29    35
5    33    30    17
6    19    37    19
7    29    29    28
8    28    22    33
9    39    24    39

In [1341]:
###

In [1342]:
tablo1 = pandas.DataFrame({"personel":["Ali","Ayse","Fatma","Enes"],
                           "departman":["Muhasebe","Mühendislik","Mühendislik","IK"]})
tablo2 = pandas.DataFrame({"personel":["Ayse","Ali","Fatma","Enes"],
                           "girisyili":[2015, 2022, 2018,2023]})
tablo3 = pandas.merge(tablo1,tablo2) # burada personelin ortak tablo oldugunu kendisi anladi ve ona göre birlestirdi.

In [1343]:
tablo1

personel    departman
0      Ali     Muhasebe
1     Ayse  Mühendislik
2    Fatma  Mühendislik
3     Enes           IK

In [1344]:
tablo2

personel  girisyili
0     Ayse       2015
1      Ali       2022
2    Fatma       2018
3     Enes       2023

In [1345]:
tablo3

personel    departman  girisyili
0      Ali     Muhasebe       2022
1     Ayse  Mühendislik       2015
2    Fatma  Mühendislik       2018
3     Enes           IK       2023

In [1346]:
###

In [1347]:
tablo4 = pandas.DataFrame({"mentor":["Caner","Mustafa","Berkcan"],
                           "departman":["Muhasebe","Mühendislik","IK"]})
tablo5 = pandas.merge(tablo3,tablo4)
# satir sayilari farkli olmasina ragmen ortak degerleri bulup tabloyu ona göre olusturdu.

In [1348]:
tablo3

personel    departman  girisyili
0      Ali     Muhasebe       2022
1     Ayse  Mühendislik       2015
2    Fatma  Mühendislik       2018
3     Enes           IK       2023

In [1349]:
tablo4

mentor    departman
0    Caner     Muhasebe
1  Mustafa  Mühendislik
2  Berkcan           IK

In [1350]:
tablo5

personel    departman  girisyili   mentor
0      Ali     Muhasebe       2022    Caner
1     Ayse  Mühendislik       2015  Mustafa
2    Fatma  Mühendislik       2018  Mustafa
3     Enes           IK       2023  Berkcan

In [1351]:
###

In [1352]:
tablo6 = pandas.DataFrame({"yetenekler":["Matematik","Programlama","EQ"],
                           "departman":["Muhasebe","Mühendislik","IK"]})
tablo7 = pandas.merge(tablo5,tablo6)

In [1353]:
tablo5

personel    departman  girisyili   mentor
0      Ali     Muhasebe       2022    Caner
1     Ayse  Mühendislik       2015  Mustafa
2    Fatma  Mühendislik       2018  Mustafa
3     Enes           IK       2023  Berkcan

In [1354]:
tablo6

yetenekler    departman
0    Matematik     Muhasebe
1  Programlama  Mühendislik
2           EQ           IK

In [1355]:
tablo7

personel    departman  girisyili   mentor   yetenekler
0      Ali     Muhasebe       2022    Caner    Matematik
1     Ayse  Mühendislik       2015  Mustafa  Programlama
2    Fatma  Mühendislik       2018  Mustafa  Programlama
3     Enes           IK       2023  Berkcan           EQ

### Aggregation

In [1356]:
import seaborn

In [1357]:
tablo = seaborn.load_dataset("planets")
tablo

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [1358]:
tablo.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [1359]:
tablo.shape

(1035, 6)

In [1360]:
tablo["distance"].mean() # distance sütunu degerilerinin ortalamasi.

264.06928217821786

In [1361]:
tablo["distance"].count() # distance sütunu degerilerin sayisi.

808

In [1362]:
tablo["distance"].min() # distance sütunu degerilerinin en kücügü.

1.35

In [1363]:
tablo["distance"].max() # distance sütunu degerilerinin en büyügü.

8500.0

In [1364]:
tablo["distance"].sum() # distance sütunu degerilerinin toplami.

213367.98000000004

In [1365]:
tablo["distance"].std() # distance sütunu degerilerinin varyansi, standart sapmasi.

733.1164929404422

In [1366]:
tablo.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [1367]:
tablo.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [1368]:
tablo.dropna().describe().T # dropna, tablodaki eksik degerleri cikartir.

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

### Grouping

In [1369]:
tablo = pandas.DataFrame({"gruplar":["A","B","C","A","B","C"],
                          "puanlar":[10,11,52,23,43,55]}, columns=["gruplar","puanlar"])

In [1370]:
tablo

gruplar  puanlar
0       A       10
1       B       11
2       C       52
3       A       23
4       B       43
5       C       55

In [1371]:
tablo.groupby("gruplar")
# tamam, gruplar sütunundaki kendini tekrar eden degerleri yakaladim. peki bununla ne yapayim?

In [1372]:
tablo.groupby("gruplar").mean() # ortalamasini al.

puanlar
gruplar         
A           16.5
B           27.0
C           53.5

In [1373]:
###

In [1374]:
tablo = seaborn.load_dataset("planets")
tablo

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [1375]:
tablo.groupby("method").sum()["orbital_period"]

method
Astrometry                       1.262360e+03
Eclipse Timing Variations        4.276480e+04
Imaging                          1.418973e+06
Microlensing                     2.207500e+04
Orbital Brightness Modulation    2.127920e+00
Pulsar Timing                    3.671511e+04
Pulsation Timing Variations      1.170000e+03
Radial Velocity                  4.553151e+05
Transit                          8.377523e+03
Transit Timing Variations        2.393505e+02
Name: orbital_period, dtype: float64

In [1376]:
tablo.groupby("method").sum()["orbital_period"].describe()

count    1.000000e+01
mean     1.986894e+05
std      4.508952e+05
min      2.127920e+00
25%      1.193090e+03
50%      1.522626e+04
75%      4.125238e+04
max      1.418973e+06
Name: orbital_period, dtype: float64

### Advanced Aggregation

In [1377]:
tablo = pandas.DataFrame({"gruplar":["A","B","C","A","B","C"],
                          "degisken1":[10,11,52,23,43,55],
                          "degisken2":[100,101,562,223,473,545]}, columns=["gruplar","degisken1","degisken2"])

In [1378]:
tablo

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        101
2       C         52        562
3       A         23        223
4       B         43        473
5       C         55        545

In [1379]:
tablo.groupby("gruplar").aggregate([min, numpy.median, max])
# dökümü bu sekilde toplu da alabiliriz.

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.5  23       100  161.5  223
B              11   27.0  43       101  287.0  473
C              52   53.5  55       545  553.5  562

In [1380]:
tablo.groupby("gruplar").aggregate({"degisken1":"min", "degisken2":"max"})
# dökümü bu sekilde toplu da alabiliriz.

degisken1  degisken2
gruplar                      
A               10        223
B               11        473
C               52        562

### Filter

In [1381]:
tablo

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        101
2       C         52        562
3       A         23        223
4       B         43        473
5       C         55        545

In [1382]:
def filtrele(x):
    return x["degisken1"].std()>3

In [1383]:
tablo.groupby("gruplar").filter(filtrele)

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        101
3       A         23        223
4       B         43        473

### Transform

In [1384]:
tablo

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        101
2       C         52        562
3       A         23        223
4       B         43        473
5       C         55        545

In [1385]:
tablo = tablo.iloc[:,1:3]
tablo

degisken1  degisken2
0         10        100
1         11        101
2         52        562
3         23        223
4         43        473
5         55        545

In [1386]:
tablo.transform(lambda x: x-x.mean() / x.std())

degisken1   degisken2
0   8.405244   98.466508
1   9.405244   99.466508
2  50.405244  560.466508
3  21.405244  221.466508
4  41.405244  471.466508
5  53.405244  543.466508

### Apply 

In [1387]:
tablo

degisken1  degisken2
0         10        100
1         11        101
2         52        562
3         23        223
4         43        473
5         55        545

In [1388]:
tablo.apply(numpy.sum)

degisken1     194
degisken2    2004
dtype: int64

### PIVOT 

In [1389]:
titanic = seaborn.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [1390]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [1391]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [1392]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [1393]:
###

In [1394]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [1395]:
titanic.pivot_table("survived", index="sex", columns="class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [1396]:
yas = pandas.cut(titanic["age"],[0,18,90])
age.head()

0    (18, 90]
1    (18, 90]
2    (18, 90]
3    (18, 90]
4    (18, 90]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [1397]:
titanic.pivot_table("survived", index=["sex", yas], columns="class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

#### Reading External Data

In [1399]:
pandas.read_csv("dizinadresi/okunacakornek.csv", sep=";")

FileNotFoundError: [Errno 2] No such file or directory: 'dizinadresi/okunacakornek.csv'